import { Artist } from './types';

export const artists: Artist[] = [
  {
    id: '1',
    name: 'Eleanora Vance',
    categories: ['singer'],
    location: 'New York, NY',
    priceRange: { min: 1000, max: 2500 },
    bio: 'A soulful singer with a powerful voice, Eleanora has captivated audiences at venues across the East Coast. Her repertoire spans jazz, blues, and contemporary pop.',
    imageUrl: 'https://placehold.co/400x400.png',
    languages: ['English', 'French'],
  },
  {
    id: '2',
    name: 'Marco Diaz',
    categories: ['dancer'],
    location: 'Los Angeles, CA',
    priceRange: { min: 800, max: 2000 },
    bio: 'A dynamic hip-hop and contemporary dancer, Marco brings energy and passion to every performance. He has worked with renowned choreographers and appeared in several music videos.',
    imageUrl: 'https://placehold.co/400x401.png',
    languages: ['English', 'Spanish'],
  },
  {
    id: '3',
    name: 'DJ Spark',
    categories: ['dj'],
    location: 'Miami, FL',
    priceRange: { min: 1200, max: 3000 },
    bio: 'Known for her eclectic mixes and ability to read any crowd, DJ Spark transforms any event into an unforgettable party. She specializes in electronic, house, and funk music.',
    imageUrl: 'https://placehold.co/400x402.png',
    languages: ['English'],
  },
  {
    id: '4',
    name: 'Dr. Anya Sharma',
    categories: ['speaker'],
    location: 'Chicago, IL',
    priceRange: { min: 2500, max: 5000 },
    bio: 'An inspiring motivational speaker and author, Dr. Sharma talks on leadership, innovation, and resilience. Her engaging talks leave audiences empowered and ready for action.',
    imageUrl: 'https://placehold.co/400x403.png',
    languages: ['English', 'Hindi'],
  },
  {
    id: '5',
    name: 'The Great Magnifico',
    categories: ['magician'],
    location: 'Las Vegas, NV',
    priceRange: { min: 1500, max: 4000 },
    bio: 'A master of illusion and sleight of hand, The Great Magnifico offers a show filled with wonder and comedy. Perfect for corporate events and private parties.',
    imageUrl: 'https://placehold.co/400x404.png',
    languages: ['English'],
  },
  {
    id: '6',
    name: 'Chloe Chen',
    categories: ['comedian'],
    location: 'San Francisco, CA',
    priceRange: { min: 700, max: 1800 },
    bio: 'With her sharp wit and relatable humor, Chloe Chen is a rising star in the stand-up comedy scene. Her observational comedy covers everything from daily life to cultural commentary.',
    imageUrl: 'https://placehold.co/400x405.png',
    languages: ['English', 'Mandarin'],
  },
    {
    id: '7',
    name: 'Isabella Rossi',
    categories: ['singer'],
    location: 'Rome, IT',
    priceRange: { min: 1500, max: 3500 },
    bio: 'An opera singer with a modern twist, Isabella brings classical beauty to contemporary events. Her voice is as powerful as it is emotive.',
    imageUrl: 'https://placehold.co/400x406.png',
    languages: ['Italian', 'English'],
  },
  {
    id: '8',
    name: 'Kenji Tanaka',
    categories: ['dancer'],
    location: 'Tokyo, JP',
    priceRange: { min: 1000, max: 2200 },
    bio: 'A butoh dancer who tells stories through movement. Kenji\'s performances are profound, artistic, and deeply moving, suitable for galleries and cultural events.',
    imageUrl: 'https://placehold.co/400x407.png',
    languages: ['Japanese', 'English'],
  },
];
